### ISSUE TITLE
Protect email from spammers

### ISSUE THREAD

**Issue by kostasx** [andreaspsass/what-is-front-end#2]
https://github.com/andreaspsass/what-is-front-end/blob/528a6d613d3fb41cd1cb6b7841eac7ae1733b84a/index.html#L162

Take a look at some ways to protect your email address [in this post](https://www.ionos.com/digitalguide/e-mail/e-mail-security/protecting-your-email-address-how-to-do-it/)

**Comment by andreaspsass** [comment]
Fixed issue on db6b0ca

I used this link to encrypt my email address https://www.knechtology.com/stop-spam/email_encoder.html?email_address=andreas.pagonis95%40gmail.com&encoded_email_address=
