### ISSUE TITLE
Fix the copyright section

### ISSUE THREAD

**Issue by kostasx** [andreaspsass/what-is-front-end#3]
https://github.com/andreaspsass/what-is-front-end/blob/528a6d613d3fb41cd1cb6b7841eac7ae1733b84a/index.html#L166

This is a very pretty page. Let's make it prettier by adding something relevant in this section.

**Comment by andreaspsass** [comment]
Fixed issue on db6b0ca

Is it prettier and more relevant now? :P

**Comment by kostasx** [comment]
Yep, that's much better. 👍
