### ISSUE TITLE
Rename suffix to .jpg

### ISSUE THREAD

**Issue by kostasx** [andreaspsass/what-is-front-end#4]
https://github.com/andreaspsass/what-is-front-end/blob/528a6d613d3fb41cd1cb6b7841eac7ae1733b84a/index.html#L42

Rename the image files to .jpg instead of .jfif and replace the references inside the HTML.

**Comment by andreaspsass** [comment]
Fixed it on 580c5ba05473046322bb410e76a1d5c6a2bc8f5a
