### ISSUE TITLE
Do the images need any kind of attribution? Fix alt attributes.

### ISSUE THREAD

**Issue by kostasx** [andreaspsass/what-is-front-end#5]
Make sure that the images used need some sort of [attribution](https://www.pixsy.com/academy/image-user/correctly-attribute-images/).

Also (and most importantly) fix the alt description with meaningful and descriptive sentences.

Compress all the images using [TinyPNG](https://tinypng.com/) and check how much smaller their file size becomes. Your pages will load much faster this way. (Tiny PNG, also works for JPG images)

**Comment by andreaspsass** [comment]
Fixed it on 580c5ba05473046322bb410e76a1d5c6a2bc8f5a, however I am not sure if the attribution is done right.

**Comment by kostasx** [comment]
Attribution must be visible at some point in the page, for example at the bottom of the page or the footer, probably using the small HTML tag.

**Comment by andreaspsass** [comment]
Fixed it on 7a059fe458730a1237da9732a91bcb09d9333fe1
