### ISSUE TITLE
Use the Chrome Lighthouse auditing tool and improve your score

### ISSUE THREAD

**Issue by kostasx** [andreaspsass/what-is-front-end#8]
You can [watch this video segment](https://www.youtube.com/watch?t=1517&v=FAhN2SzC7Os&feature=youtu.be) and learn how to audit your webpage using the Lighthouse Auditing tool

Once you have the report, follow the suggested fixes to get the best possible score.

**Comment by andreaspsass** [comment]
fixed on aeaadde6310a48ef9be8b150265e0e7d046678ba
