### ISSUE TITLE
Make sure to fix any W3C validator errors

### ISSUE THREAD

**Issue by kostasx** [andreaspsass/what-is-front-end#9]
Run your source HTML code through the [W3C Validator](https://validator.w3.org/) and fix as many errors and warnings as possible.

**Comment by andreaspsass** [comment]
Fixed on f62c84de54bd6d7b976966543e7bfb7d9c21a8d5

**Comment by andreaspsass** [comment]
Fixed on 3a30f08cf365ae312d120bacee5df87b1a4a78ad

Is there another way to check with the w3c validator cause it gets tiring and messy with continuous git commits when testing

**Comment by kostasx** [comment]
Yes, I know what you mean. Maybe do a validation test at the end of all the changes. Alternatively, you can try this [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=CelianRiboulet.webvalidator) or if you feel adventurous, you can try this [command line tool](https://github.com/zrrrzzt/html-validator-cli#readme).
